export const GET_BALANCE = 'GET_BALANCE';
export const LOGIN = 'LOGIN';
export const WALLET_CONNECT_CHECK = 'WALLET_CONNECT_CHECK';
export const SET_CHAINID = 'SET_CHAINID';
export const WALLET_BALANCE = 'WALLET_BALANCE';
export const LOGIN_CHECK="LOGIN_CHECK";
export const SIGNUP_CHECK="SIGNUP_CHECK";
export const CREATE_COLLECTION="CREATE_COLLECTION";